"""Run the precision corpus → console summary + ``docs/PRECISION.md`` + ``corpus/results.json``.

Usage::

    python -m corpus.measure              # spin a throwaway Postgres, write the report
    DATABASE_URL=... python -m corpus.measure   # measure against an existing DB
    python -m corpus.measure --print      # console only, don't write files

The published numbers in ``docs/PRECISION.md`` are regenerated by this
script; ``tests/test_corpus_precision.py`` re-runs the measurement in CI
and fails if any case drifts from its label, so the report cannot rot
silently.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

from pgrls import __version__

from corpus.harness import CaseResult, Summary, corpus_db, measure, summarize

ROOT = Path(__file__).resolve().parent.parent
REPORT_PATH = ROOT / "docs" / "PRECISION.md"
RESULTS_PATH = ROOT / "corpus" / "results.json"


def _measure_with_db() -> list[CaseResult]:
    with corpus_db() as url:
        return measure(url)


def _pct(x: float | None) -> str:
    return "—" if x is None else f"{x * 100:.1f}%"


def render_markdown(summary: Summary) -> str:
    lines: list[str] = []
    lines.append("# pgrls precision corpus")
    lines.append("")
    lines.append(
        "Generated by `python -m corpus.measure` "
        f"(pgrls {__version__}). Do not edit by hand — re-run the script."
    )
    lines.append("")
    lines.append("## What this is")
    lines.append("")
    lines.append(
        "An **adjudicated** corpus of small, self-contained schemas, each "
        "linted through the real introspection + rule path with the full "
        "built-in rule set at default options (no `disable`, no allowlists). "
        "Every case carries the complete set of rule IDs that *should* fire; "
        "anything else that fires is a false positive, anything missing is a "
        "false negative."
    )
    lines.append("")
    lines.append(
        "The negatives are deliberately **adversarial** — `coalesce()`-"
        "wrapped auth checks, `IS NULL` buried in subqueries or under `AND`, "
        "predicates wrapped in `SubLink`s — the exact shapes that bait false "
        "positives. A clean schema that trivially fires nothing would prove "
        "nothing."
    )
    lines.append("")
    lines.append(
        "> **Scope caveat.** This measures *construct validity* — whether "
        "pgrls fires correctly on hand-labeled cases. It is **not** a random "
        "sample of real-world databases, so these are a precision/recall "
        "characterization of this labeled set, not an estimate of the "
        "false-positive rate over all Postgres schemas in the wild. The two "
        "artifact-dependent rules (HYG004 coverage, PERF005 runtime stats) "
        "need data a static schema doesn't have and are out of scope."
    )
    lines.append("")
    lines.append("## Headline")
    lines.append("")
    lines.append(
        f"- **{summary.n_cases}** cases "
        f"({summary.n_positive} positive, {summary.n_negative} negative/near-miss)"
    )
    lines.append(
        f"- **{summary.tp_total}** true positives, "
        f"**{summary.fp_total}** false positives, "
        f"**{summary.fn_total}** false negatives"
    )
    lines.append(f"- **Precision:** {_pct(summary.precision)}")
    lines.append(f"- **Recall:** {_pct(summary.recall)}")
    lines.append("")
    if summary.undocumented_fp:
        lines.append("### ⚠ Undocumented false positives")
        lines.append("")
        for name, rules in summary.undocumented_fp:
            lines.append(f"- `{name}`: {', '.join(sorted(rules))}")
        lines.append("")
    if summary.known_fp:
        lines.append("### Known false positives (tracked, not yet fixed)")
        lines.append("")
        for name, rules in summary.known_fp:
            lines.append(f"- `{name}`: {', '.join(sorted(rules))}")
        lines.append("")
    lines.append("## Per-rule")
    lines.append("")
    lines.append("Only rules with activity (≥1 expected or fired) are shown.")
    lines.append("")
    lines.append("| Rule | TP | FP | FN | Precision | Recall |")
    lines.append("|------|----|----|----|-----------|--------|")
    for rid in sorted(summary.per_rule):
        st = summary.per_rule[rid]
        if st.tp == 0 and st.fp == 0 and st.fn == 0:
            continue
        lines.append(
            f"| {rid} | {st.tp} | {st.fp} | {st.fn} | "
            f"{_pct(st.precision)} | {_pct(st.recall)} |"
        )
    lines.append("")
    return "\n".join(lines)


def _results_json(results: list[CaseResult], summary: Summary) -> str:
    payload = {
        "pgrls_version": __version__,
        "totals": {
            "cases": summary.n_cases,
            "positive": summary.n_positive,
            "negative": summary.n_negative,
            "tp": summary.tp_total,
            "fp": summary.fp_total,
            "fn": summary.fn_total,
            "precision": summary.precision,
            "recall": summary.recall,
        },
        "cases": [
            {
                "name": r.case.name,
                "kind": r.case.kind,
                "expect": sorted(r.case.expect),
                "fired": sorted(r.fired),
                "false_positives": sorted(r.false_positives),
                "false_negatives": sorted(r.false_negatives),
            }
            for r in results
        ],
    }
    return json.dumps(payload, indent=2)


def _print_dump(results: list[CaseResult], summary: Summary) -> None:
    for r in results:
        fp = sorted(r.false_positives)
        fn = sorted(r.false_negatives)
        flag = "OK " if not fp and not fn else "!! "
        print(
            f"{flag}{r.case.kind[:3]} {r.case.name}\n"
            f"     expect={sorted(r.case.expect)} fired={sorted(r.fired)}"
            + (f" FP={fp}" if fp else "")
            + (f" FN={fn}" if fn else "")
        )
    print(
        f"\n{summary.n_cases} cases | "
        f"TP={summary.tp_total} FP={summary.fp_total} FN={summary.fn_total} | "
        f"precision={_pct(summary.precision)} recall={_pct(summary.recall)}"
    )


def main() -> int:
    print_only = "--print" in sys.argv
    results = _measure_with_db()
    summary = summarize(results)
    _print_dump(results, summary)
    if not print_only:
        REPORT_PATH.write_text(render_markdown(summary) + "\n", encoding="utf-8")
        RESULTS_PATH.write_text(_results_json(results, summary) + "\n", encoding="utf-8")
        print(f"\nwrote {REPORT_PATH.relative_to(ROOT)} and {RESULTS_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
