"""Shared helpers for the standalone-HTML formatters.

`pgrls lint --format html` (`formatters.html`), `pgrls report
--format html` (`report`), `pgrls history --format html` (`history`),
and `pgrls diff --format html` (`diff.formatters`) each render a
self-contained HTML document carrying a generation timestamp. All four
honour the same `generated_at` contract:

* `None` → `datetime.now(timezone.utc)`;
* a timezone-aware datetime → normalised to UTC;
* a *naive* datetime → `ValueError`, because interpreting it as local
  time would stamp a wrong audit time depending on the host.

That contract was copy-pasted verbatim across the four formatters
(only the function-name prefix in the error differed). It lives here
now so the contract has one definition.

The five timestamped HTML renderers (coverage / perf / report /
history / diff) also share a document *scaffold* — the
`<!DOCTYPE html>` → `<head>` → `<style>` → `<header>` (h1 + a
"Generated by `<code>…</code>` · <ts>" meta line) → {body} →
`<footer>` frame — and the *common* CSS lines that frame their
intentionally-divergent per-page rules. `html_page` renders the
scaffold; `BASE_CSS_HEAD` / `BASE_CSS_TAIL` are the CSS lines every
one of those pages shares (the `:root`, `body`, the shared head of
the dark-mode block, `.empty`, `footer`). Each renderer passes only
its *own* CSS — the divergent dark-mode striping, the semantic
status / classification colours, the per-page table tweaks — as
`extra_css`, which `html_page` splices between the shared head and
tail. The full per-page stylesheet is therefore
`BASE_CSS_HEAD + extra_css + BASE_CSS_TAIL`, byte-identical to the
hand-written block each renderer used to carry.

`pgrls explain --format html` (`cli`) renders no timestamp (so it
doesn't use the timestamp helpers) and carries a deliberately
different body stylesheet (a wider `1.55` line-height, a `<pre>`
reference block) and a custom header/footer, so it does *not* route
through `html_page` / `BASE_CSS_*`; the two explain renderers share
their own `_explain_html_css` helper in `cli`.
"""
from __future__ import annotations

from datetime import datetime, timezone

# The CSS lines every timestamped HTML page shares, split into the head
# (everything up to — but not including — the dark-mode striping rules,
# which diverge per page) and the tail (`.empty` + `footer`, the common
# trailing rules). A page's full stylesheet is
# `BASE_CSS_HEAD.format(max_width=…) + extra_css + BASE_CSS_TAIL`, where
# `extra_css` is the page's own middle block. `{max_width}` is the only
# parameter — coverage / perf / report use `64rem`, history / diff `72rem`.
BASE_CSS_HEAD = """  :root {{ color-scheme: light dark; }}
  body {{ font: 14px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI",
         Roboto, "Helvetica Neue", Arial, sans-serif;
         margin: 2rem auto; max-width: {max_width}; padding: 0 1rem;
         color: #1f2328; background: #ffffff; }}
  @media (prefers-color-scheme: dark) {{
    body {{ color: #e6edf3; background: #0d1117; }}
    table {{ border-color: #30363d; }}
    th {{ background: #161b22; }}"""

BASE_CSS_TAIL = """  .empty { text-align: center; color: #57606a; padding: 1.5rem; }
  footer { margin-top: 2rem; color: #57606a; font-size: .8rem; }"""


def resolve_generated_at(
    generated_at: datetime | None,
    *,
    caller_name: str,
) -> datetime:
    """Resolve the `generated_at` argument the HTML formatters accept.

    `None` defaults to `datetime.now(timezone.utc)`. A naive datetime
    raises `ValueError` (a silent local-time coercion would produce a
    wrong audit timestamp depending on the host). `caller_name` is the
    public function name, used as the error-message prefix so the
    message reads identically to the hand-written one each formatter
    used to carry.
    """
    if generated_at is None:
        return datetime.now(timezone.utc)
    if generated_at.tzinfo is None:
        raise ValueError(
            f"{caller_name}: generated_at must be timezone-aware; "
            "a naive datetime would be interpreted as local time, "
            "producing a wrong audit timestamp depending on the "
            "host. Pass `datetime.now(timezone.utc)` or attach an "
            "explicit tzinfo."
        )
    return generated_at


def to_iso_z(generated_at: datetime) -> str:
    """Render a tz-aware datetime as an ISO-8601 UTC string with a
    `Z` suffix and second precision — e.g. `2026-05-27T16:00:00Z`.

    Mirrors the chain every HTML formatter used inline:
    `.astimezone(utc).replace(microsecond=0).isoformat()` with the
    `+00:00` offset rewritten to `Z`.
    """
    return (
        generated_at
        .astimezone(timezone.utc)
        .replace(microsecond=0)
        .isoformat()
        .replace("+00:00", "Z")
    )


def html_page(
    *,
    title: str,
    heading: str,
    command: str,
    generated_at_iso: str,
    body: str,
    extra_css: str = "",
    max_width: str = "64rem",
    header_extra: str = "",
    footer_extra: str = "",
) -> str:
    """Assemble a timestamped standalone HTML page.

    Renders the scaffold the five timestamped renderers share:
    `<!DOCTYPE html>` → `<head>` (with `<title>{title}` and a
    `<style>` of `BASE_CSS_HEAD + extra_css + BASE_CSS_TAIL`) →
    `<body>` → `<header>` (an `<h1>{heading}` plus a
    `Generated by <code>{command}</code> · {ts}` meta line, then
    `header_extra`) → `{body}` → the shared `<footer>` (with an
    optional `footer_extra` suffix) → close.

    Arguments:

    * `title` — the `<title>` text (already escaped by the caller if
      it interpolates anything; in practice every caller passes a
      constant).
    * `heading` — the `<h1>` text.
    * `command` — the `pgrls … --format html` invocation shown inside
      `<code>` in the meta line.
    * `generated_at_iso` — the already-escaped ISO-Z timestamp string
      (callers pass `html.escape(to_iso_z(generated_at))`).
    * `body` — the content between `</header>` and `<footer>`,
      typically the `<table>…</table>` block (plus, for perf, an
      optional statements section). Inserted verbatim — the caller
      owns its indentation and any HTML-escaping of cell values.
    * `extra_css` — the page's own CSS lines (dark-mode striping,
      semantic colours, table tweaks), spliced between
      `BASE_CSS_HEAD` and `BASE_CSS_TAIL`.
    * `max_width` — the `body { max-width }` value (`64rem` default;
      history / diff pass `72rem`).
    * `header_extra` — already-indented HTML inserted after the meta
      line and before `</header>` (the summary band / status pills /
      caveat). Empty by default.
    * `footer_extra` — an already-built suffix appended inside the
      `<footer>` after the GitHub link, before `</footer>` (history
      passes ` · <em>…</em>`). Empty by default.

    The full per-page stylesheet is
    `BASE_CSS_HEAD.format(max_width) + "\\n" + extra_css + "\\n" +
    BASE_CSS_TAIL`, byte-identical to the inlined `<style>` each
    renderer used to carry.
    """
    css = (
        BASE_CSS_HEAD.format(max_width=max_width)
        + "\n"
        + extra_css
        + "\n"
        + BASE_CSS_TAIL
    )
    header_extra_block = f"\n{header_extra}" if header_extra else ""
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{title}</title>
<style>
{css}
</style>
</head>
<body>
  <header>
    <h1>{heading}</h1>
    <p class="meta">Generated by <code>{command}</code> · {generated_at_iso}</p>{header_extra_block}
  </header>
{body}
  <footer>pgrls — Postgres Row-Level Security linter · <a href="https://github.com/pgrls/pgrls">github.com/pgrls/pgrls</a>{footer_extra}</footer>
</body>
</html>
"""
