"""Auto-remediation for the rules whose fix is mechanical.

Not every rule is auto-fixable. SEC003 (which role to grant to?),
SEC005 (which column to scope by?), SEC009 (what policy should be
added?) require human intent. Rules listed here have a single
correct fix that pgrls can generate without asking.

Usage:

    from pgrls.fixers import default_fixers, generate_fixes
    fixes = generate_fixes(schema, options, rule_filter=None)
    for fix in fixes:
        print(fix.sql)

`pgrls fix` (CLI) wires this up. Default mode is dry-run — print
the SQL but don't execute. `--apply` runs each statement on the
configured database.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Protocol, runtime_checkable

from pgrls.model import Schema

__all__ = [
    "Fix",
    "Fixer",
    "default_fixers",
    "generate_fixes",
    "render_fixes",
    "render_migration",
]


@dataclass(frozen=True)
class Fix:
    """A single SQL statement that remediates one violation."""

    rule_id: str
    location: str
    sql: str
    description: str


@runtime_checkable
class Fixer(Protocol):
    """Per-rule fixer. Returns one Fix per offending policy/table."""

    rule_id: str

    def fix(
        self, schema: Schema, options: dict[str, Any]
    ) -> list[Fix]: ...


def default_fixers() -> list[Fixer]:
    """Every fixer the project ships."""
    from pgrls.fixers.hyg003 import HYG003Fixer
    from pgrls.fixers.perf001 import PERF001Fixer
    from pgrls.fixers.perf003 import PERF003Fixer
    from pgrls.fixers.sec001 import SEC001Fixer
    from pgrls.fixers.sec002 import SEC002Fixer
    from pgrls.fixers.sec006 import SEC006Fixer
    from pgrls.fixers.sec011 import SEC011Fixer
    from pgrls.fixers.sec019 import SEC019Fixer
    from pgrls.fixers.sec020 import SEC020Fixer
    from pgrls.fixers.view001 import VIEW001Fixer
    from pgrls.fixers.view002 import VIEW002Fixer

    return [
        SEC001Fixer(),
        SEC002Fixer(),
        SEC006Fixer(),
        SEC011Fixer(),
        SEC019Fixer(),
        SEC020Fixer(),
        PERF001Fixer(),
        PERF003Fixer(),
        HYG003Fixer(),
        VIEW001Fixer(),
        VIEW002Fixer(),
    ]


def generate_fixes(
    schema: Schema,
    rule_options: dict[str, dict[str, Any]],
    *,
    rule_filter: set[str] | None = None,
) -> list[Fix]:
    """Run every fixer (or just the ones in `rule_filter`) and
    return the union of Fix objects, ordered by (rule_id, location).

    Each fixer validates its rule's `allowlist` option with the
    rule's strict parser; a malformed allowlist raises `TypeError`,
    which `pgrls fix` surfaces as a tool error — the same failure
    `pgrls lint` produces for the same config.

    Sort is alphabetical by `rule_id` then `location`. Today's
    fixers emit independent statements (`ALTER TABLE`, `ALTER
    VIEW`, `ALTER POLICY`), so the ordering is correctness-
    irrelevant. A future fixer that depends on order (e.g. CREATE
    POLICY before its referenced table is forced) will need
    explicit dependency-based ordering — the alphabetical sort is
    incidental, not guaranteed.
    """
    out: list[Fix] = []
    for fixer in default_fixers():
        if rule_filter is not None and fixer.rule_id not in rule_filter:
            continue
        opts = rule_options.get(fixer.rule_id, {})
        out.extend(fixer.fix(schema, opts))
    return sorted(out, key=lambda f: (f.rule_id, f.location))


def render_fixes(fixes: list[Fix]) -> str:
    """Render `fixes` as `-- [RULE] description` + SQL blocks.

    One block per fix — a comment line naming the rule and
    describing the change, then the SQL statement. Blocks are
    separated by a blank line. No trailing newline; the caller
    adds one (`click.echo` does, `render_migration` does).

    This is the body shared by `pgrls fix`'s stdout dry-run and
    the `--output` migration file, so the two never drift.
    """
    return "\n\n".join(
        f"-- [{fix.rule_id}] {fix.description}\n{fix.sql}"
        for fix in fixes
    )


def render_migration(fixes: list[Fix], *, tool_version: str) -> str:
    """Render `fixes` as a complete migration-ready `.sql` script.

    The text is a header comment — naming the generating pgrls
    version and the fix count — followed by the `render_fixes`
    blocks and a single trailing newline. `pgrls fix --output`
    writes exactly this.

    Deterministic: the header carries no timestamp, so
    regenerating against an unchanged schema produces a
    byte-identical file (clean diffs when the migration is
    committed). The fixes themselves are already ordered by
    `generate_fixes` (`(rule_id, location)`).
    """
    count = len(fixes)
    plural = "fix" if count == 1 else "fixes"
    header = (
        f"-- Remediation SQL generated by pgrls {tool_version}.\n"
        "--\n"
        "-- Review every statement before applying. Generated from\n"
        "-- a snapshot of the database; regenerate if the schema\n"
        f"-- has changed since. {count} {plural}.\n"
    )
    return f"{header}\n{render_fixes(fixes)}\n"
